spring:
  application:
    name: accounts-service
  cloud:
    config:
      uri: http://config-server:8888/
      import:
        optional:configserver:
      enabled: false
    refresh:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${dh.keycloak.clientId}
            client-secret: ${dh.keycloak.clientSecret}
            scope: openid
            #realm: ${dh.keycloak.realm}
            #serverUrl: ${dh.keycloak.serverUrl}
        provider:
          keycloak:
            issuer-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}
      resourceserver:
        jwt:
          issuer-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}
          #jwk-set-uri: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}/protocol/openid-connect/certs


dh:
  keycloak:
    realm: ${REALM_NAME}
    serverUrl: http://keycloak:8080
    clientId: ${CLIENT_ID}
    clientSecret: ${CLIENT_SECRET}
    #tokenEndpoint: ${dh.keycloak.serverUrl}/realms/${dh.keycloak.realm}/protocol/openid-connect/token

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: accounts-service
    description: microservicio de administracion de billetera virtual (docker)
    version: 1.0.0

eureka:
  instance:
    hostname: accounts-service
    #hostname: localhost
    #ip-address: 127.0.0.1
    prefer-ip-address: false
    statusPageUrlPath: http://accounts-service:8082/actuator/info
    healthCheckUrlPath: http://accounts-service:8082/actuator/health
    #statusPageUrlPath: http://localhost:8082/actuator/info
    #healthCheckUrlPath: http://localhost:8082/actuator/health
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka
server:
  port: 8082

logging:
  level:
    org.springframework.cloud.openfeign: DEBUG

    feign.Logger: DEBUG
