spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: cards-service
    description: microservicio de administracion y registro de tarjetas de credito y debito (github)
    version: 1.0.0

eureka:
  instance:
    prefer-ip-address: false
    statusPageUrlPath: http://localhost:8085/actuator/info
    healthCheckUrlPath: http://localhost:8085/actuator/health
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8085



