spring:
  application:
    name: transactions-service
  cloud:
    config:
      uri: http://config-server:8888/
      import:
        optional:configserver:
      enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.event.merge.entity_copy_observer: allow
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: ${DB_DRIVER}

management:
  endpoints:
    web:
      exposure:
        include: health, info
  info:
    env:
      enabled: true
info:
  app:
    name: transactions-service
    description: microservicio de administracion y registro de transacciones entre usuarios (local)
    version: 1.0.0

eureka:
  instance:
    hostname: transactions-service
    #hostname: localhost
    #ip-address: 127.0.0.1
    prefer-ip-address: false
    statusPageUrlPath: http://transactions-service:8083/actuator/info
    healthCheckUrlPath: http://transactions-service:8083/actuator/health
    #statusPageUrlPath: http://localhost:8083/actuator/info
    #healthCheckUrlPath: http://localhost:8083/actuator/health
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/
      #defaultZone: http://localhost:8761/eureka

server:
  port: 8083
